name: Test setup
description: "Setup the environment for the CI"

runs:
  using: "composite"
  steps:
    - name: Install Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        cache-dependency-path: "**/go.sum"

    - name: Print go version
      shell: bash
      run: go version

    - name: Setup toolchain
      id: rustc-toolchain
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh
        . "$HOME/.zkm-toolchain/env"
